# Generated by Django 3.2.9 on 2022-08-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_auto_20220803_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_desc',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
